"""
This type stub file was generated by the AI agent.
"""

from .api import parse
from .datetimes import registerDateHandler
from .exceptions import (
    CharacterEncodingOverride,
    CharacterEncodingUnknown,
    NonXMLContentType,
    ThingsNobodyCaresAboutButMe,
    UndeclaredNamespace,
)
from .util import FeedParserDict

__all__ = [
    "parse",
    "registerDateHandler",
    "FeedParserDict",
    "ThingsNobodyCaresAboutButMe",
    "CharacterEncodingOverride",
    "CharacterEncodingUnknown",
    "NonXMLContentType",
    "UndeclaredNamespace",
]
