"""
This type stub file was generated by the AI agent.
"""

__all__ = [
    "ThingsNobodyCaresAboutButMe",
    "CharacterEncodingOverride",
    "CharacterEncodingUnknown",
    "NonXMLContentType",
    "UndeclaredNamespace",
]

class ThingsNobodyCaresAboutButMe(Exception): ...
class CharacterEncodingOverride(ThingsNobodyCaresAboutButMe): ...
class CharacterEncodingUnknown(ThingsNobodyCaresAboutButMe): ...
class NonXMLContentType(ThingsNobodyCaresAboutButMe): ...
class UndeclaredNamespace(Exception): ...
