"""
This type stub file was generated by the AI agent.
"""

from time import struct_time
from typing import Literal, TypedDict

class Item(TypedDict):
    id: str
    title: str
    description: str
    link: str
    links: list[Link]
    published: str
    published_parsed: struct_time
    updated: str
    updated_parsed: struct_time
    guidislink: bool
    content: list[SummaryDetail]
    summary: str
    authors: list[dict[str, str]]
    author_detail: dict[str, str]
    author: str
    tags: list[Tag]
    summary_detail: SummaryDetail
    media_thumbnail: list[Media]
    media_content: list[Media]

class Media(TypedDict):
    url: str

class Tag(TypedDict):
    term: str
    scheme: str
    label: str

class Link(TypedDict):
    href: str
    rel: Literal["alternate", "enclosure"]
    type: Literal["text/html", "image/png", "image/jpeg"]
    title: str

class SummaryDetail:
    type: Literal["text/html"] | None
    language: str | None
    base: str | None
    value: str

class FeedParserDict:
    entries: list[Item]
