"""
This type stub file was generated by the AI agent.
"""

from time import struct_time
from typing import Callable

def registerDateHandler(func: Callable[[str], struct_time | None]) -> None:
    """Register a date handler function (takes string, returns 9-tuple date in GMT)"""
    ...

def _parse_date(date_str: str) -> struct_time | None: ...
